module.exports = {
  JWT_SECRET: process.env.JWT_SECRET || 'finance-dashboard-secret-key-change-in-production',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '24h',
  PORT: process.env.PORT || 3000,
  ROLES: {
    VIEWER: 'viewer',
    ANALYST: 'analyst',
    ADMIN: 'admin',
  },
  RECORD_TYPES: ['income', 'expense'],
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  CATEGORIES: [
    'salary',
    'freelance',
    'investment',
    'food',
    'transport',
    'utilities',
    'entertainment',
    'healthcare',
    'education',
    'shopping',
    'rent',
    'insurance',
    'savings',
    'other',
  ],
};
